version: 2.1
orbs:
  node: circleci/node@5

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run: echo "Building things..."
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: with-jest-app

  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/unit
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          command: echo "Running Unit Tests..."
          working_directory: with-jest-app
      - store_test_results:
          path: with-jest-app/test-results/unit

  integration-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/integration
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Integration Tests
          command: echo "Running Integration Tests..."
          working_directory: with-jest-app
      - store_test_results:
          path: with-jest-app/test-results/integration

  regression-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/regression
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Regression Tests
          command: echo "Running Regression Tests..."
          working_directory: with-jest-app
      - store_test_results:
          path: with-jest-app/test-results/regression

  performance-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Performance Tests
          command: echo "Running Performance Tests..."
          working_directory: with-jest-app

  security-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Security Tests
          command: echo "Running Security Tests..."
          working_directory: with-jest-app

  compatibility-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Compatibility Tests
          command: echo "Running Compatibility Tests..."
          working_directory: with-jest-app

  accessibility-tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          name: Run Accessibility Tests
          command: echo "Running Accessibility Tests..."
          working_directory: with-jest-app

  prepare-deployment:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Prepare Deployment Environment
          command: echo "Preparing deployment environment..."

  deploy-application:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application..."

  verification-tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run Verification Tests
          command: echo "Running verification tests..."
  prepare-staging:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Prepare Staging Environment
          command: echo "Preparing staging environment..."

  deploy-to-staging:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploy to Staging
          command: echo "Deploying to staging environment..."


  functional-validation-tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run Functional Validation Tests
          command: echo "Running functional validation tests..."

  load-tests:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run Load Tests
          command: echo "Running load tests..."

  deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "Final deployment step..."

  monitoring:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Monitor and Follow-up
          command: echo "Monitoring and follow-up..."

workflows:
  version: 2

  develop_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - integration-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - regression-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - security-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
      - prepare-staging:
          requires:
            - integration-tests
          filters:
            branches:
              only:
                - develop
      - deploy-to-staging:
          requires:
            - prepare-staging
          filters:
            branches:
              only:
                - develop
      - functional-validation-tests:
          requires:
            - deploy-to-staging
          filters:
            branches:
              only:
                - develop
      - load-tests:
          requires:
            - deploy-to-staging
          filters:
            branches:
              only:
                - develop
      - monitoring:
          requires:
            - load-tests
          filters:
            branches:
              only:
                - develop

  integration_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - integration
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - integration-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - regression-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - performance-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - security-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - compatibility-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - accessibility-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - integration
      - prepare-staging:
          requires:
            - compatibility-tests
          filters:
            branches:
              only:
                - integration
      - deploy-to-staging:
          requires:
            - prepare-staging
          filters:
            branches:
              only:
                - integration
      - functional-validation-tests:
          requires:
            - deploy-to-staging
          filters:
            branches:
              only:
                - integration
      - load-tests:
          requires:
            - deploy-to-staging
          filters:
            branches:
              only:
                - integration
      - monitoring:
          requires:
            - load-tests
          filters:
            branches:
              only:
                - integration

  production_workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - integration-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - regression-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - performance-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - security-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - compatibility-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - accessibility-tests:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - prepare-deployment:
          requires:
            - build
          filters:
            branches:
              only:
                - main
      - deploy-application:
          requires:
            - prepare-deployment
          filters:
            branches:
              only:
                - main
      - verification-tests:
          requires:
            - deploy-application
          filters:
            branches:
              only:
                - main
      - functional-validation-tests:
          requires:
            - deploy-application
          filters:
            branches:
              only:
                - main
      - load-tests:
          requires:
            - deploy-application
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - load-tests
          filters:
            branches:
              only:
                - main
      - monitoring:
          requires:
            - deploy
          filters:
            branches:
              only:
                - main

  feature_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^feature.*/
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^feature.*/
      - security-tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^feature.*/

  hotfix_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^hotfix.*/
      - unit-tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^hotfix.*/
      - security-tests:
          requires:
            - build
          filters:
            branches:
              ignore:
                - develop
                - integration
                - main
              only:
                - /^hotfix.*/
