version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run: echo "Building things..."
      - run:
          name: Install Dependencies
          command: npm install
          working_directory: with-jest-app
      # - run:
      #     name: Clean and Package
      #     command: npm run build
      #     working_directory: with-jest-app
  unit-tests:
    executor: node/default
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          app-dir: with-jest-app
      - run:
          command: npm install jest-junit
          working_directory: with-jest-app
      - run:
          name: Run tests
          command: npm run test:ci
          working_directory: with-jest-app
      - store_test_results:
          path: with-jest-app/test-results/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit-tests:
          requires:
            - build
